# .github/workflows/jscpd.yml
name: jscpd Check

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch: # This allows manual triggering

jobs:
  jscpd:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install jscpd

    - name: Run jscpd
      run: npx jscpd
